# ============================================================
# File    : bot.py
# Purpose : Main entry point — registers all handlers and starts the bot
# Author  : Generated by AI
# ============================================================

import asyncio
import logging
import sys
from telegram import Update, BotCommand
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    CallbackQueryHandler,
    filters,
    ContextTypes,
)

# ── Logging setup ──────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("telegram").setLevel(logging.WARNING)
logger = logging.getLogger(__name__)

# ── Config & DB ────────────────────────────────────────────
from config import BOT_TOKEN, OWNER_ID, ADMIN_IDS
from database.mongodb import connect_db, close_db

# ── Handlers ───────────────────────────────────────────────
from handlers.start import start_command, help_command, home_callback, help_callback
from handlers.force_join import handle_verify_stage1, handle_verify_stage2
from handlers.upload import handle_upload, handle_category_selection
from handlers.links import (
    my_links_page_callback, view_file_callback, file_stats_callback,
    copy_link_callback, delete_file_callback, confirm_delete_callback,
    my_stats_callback,
)
from handlers.admin import (
    show_admin_panel, admin_panel_callback, admin_stats_callback,
    admin_users_callback, admin_view_user_callback,
    admin_ban_callback, admin_receive_ban_reason, admin_unban_callback,
    admin_reset_verify_callback, admin_files_callback,
    admin_view_file_callback, admin_delete_file_callback,
    admin_disable_file_callback, admin_mark_permanent_callback,
    ban_command, unban_command, stats_command,
)
from handlers.owner import (
    show_owner_panel, owner_panel_callback, owner_admins_callback,
    owner_bc_history_callback, owner_command, add_admin_command,
    remove_admin_command, owner_info_command,
)
from handlers.broadcast import (
    start_broadcast_flow, receive_broadcast_message,
    execute_broadcast_callback, stop_broadcast_callback,
    cancel_broadcast_callback,
)
from handlers.settings import (
    show_settings, settings_callback,
    toggle_notifications_callback, toggle_language_callback,
    settings_command,
)


# ── Smart message router ───────────────────────────────────

async def smart_message_router(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Routes incoming messages intelligently:
    - If user is in broadcast_mode → capture as broadcast content
    - If user is awaiting ban reason → capture as ban reason
    - Otherwise → handle as file upload or menu button
    """
    user = update.effective_user
    if not user:
        return

    # Check if admin/owner is in broadcast compose mode
    if context.user_data.get("broadcast_mode") and (
        user.id == OWNER_ID or user.id in ADMIN_IDS
    ):
        await receive_broadcast_message(update, context)
        return

    # Check if admin is awaiting ban reason
    if context.user_data.get("awaiting_ban_reason") and (
        user.id == OWNER_ID or user.id in ADMIN_IDS
    ):
        await admin_receive_ban_reason(update, context)
        return

    # Normal message → upload or button handler
    await handle_upload(update, context)


# ── Bot commands registration ──────────────────────────────

async def set_bot_commands(app: Application) -> None:
    """Register bot commands visible in Telegram."""
    user_commands = [
        BotCommand("start", "Start the bot / Main menu"),
        BotCommand("help", "Help and instructions"),
        BotCommand("mylinks", "View your uploaded files"),
        BotCommand("mystats", "Your personal statistics"),
        BotCommand("settings", "Manage your preferences"),
    ]
    admin_commands = user_commands + [
        BotCommand("admin", "Open admin panel"),
        BotCommand("stats", "Bot statistics"),
        BotCommand("ban", "Ban a user: /ban user_id reason"),
        BotCommand("unban", "Unban a user: /unban user_id"),
    ]
    owner_commands = admin_commands + [
        BotCommand("owner", "Open Owner Control Center"),
        BotCommand("broadcast", "Start manual broadcast"),
        BotCommand("addadmin", "Promote to admin: /addadmin user_id"),
        BotCommand("removeadmin", "Demote admin: /removeadmin user_id"),
        BotCommand("ownerinfo", "Bot health info"),
    ]

    try:
        from telegram import BotCommandScopeAllPrivateChats, BotCommandScopeChat
        await app.bot.set_my_commands(user_commands, scope=BotCommandScopeAllPrivateChats())
        await app.bot.set_my_commands(owner_commands, scope=BotCommandScopeChat(OWNER_ID))
        for aid in ADMIN_IDS:
            try:
                await app.bot.set_my_commands(admin_commands, scope=BotCommandScopeChat(aid))
            except Exception:
                pass
        logger.info("Bot commands registered.")
    except Exception as e:
        logger.warning(f"Could not set commands: {e}")


# ── Startup ────────────────────────────────────────────────

async def on_startup(app: Application) -> None:
    """Called after bot starts."""
    await connect_db()
    await set_bot_commands(app)
    logger.info(f"Bot started! Owner: {OWNER_ID} | Admins: {ADMIN_IDS}")
    try:
        await app.bot.send_message(OWNER_ID, "✅ Bot is online and ready!")
    except Exception:
        pass


async def on_shutdown(app: Application) -> None:
    """Called before bot stops."""
    await close_db()
    logger.info("Bot shut down gracefully.")


# ── Error handler ──────────────────────────────────────────

async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Log errors and notify owner."""
    logger.error(f"Exception: {context.error}", exc_info=context.error)
    try:
        await context.bot.send_message(
            OWNER_ID,
            f"⚠️ *Bot Error*\n`{str(context.error)[:200]}`",
            parse_mode="Markdown",
        )
    except Exception:
        pass


# ── Handler registration ───────────────────────────────────

def register_handlers(app: Application) -> None:
    """Register all handlers in the correct order."""

    # ── Commands ──────────────────────────────────────────
    app.add_handler(CommandHandler("start", start_command))
    app.add_handler(CommandHandler("help", help_command))
    app.add_handler(CommandHandler("settings", settings_command))
    app.add_handler(CommandHandler("mystats", lambda u, c: my_stats_callback(u, c)))
    app.add_handler(CommandHandler("mylinks", lambda u, c: show_settings(u, c)))

    # Admin commands
    app.add_handler(CommandHandler("admin", show_admin_panel))
    app.add_handler(CommandHandler("stats", stats_command))
    app.add_handler(CommandHandler("ban", ban_command))
    app.add_handler(CommandHandler("unban", unban_command))

    # Owner commands
    app.add_handler(CommandHandler("owner", owner_command))
    app.add_handler(CommandHandler("broadcast", start_broadcast_flow))
    app.add_handler(CommandHandler("addadmin", add_admin_command))
    app.add_handler(CommandHandler("removeadmin", remove_admin_command))
    app.add_handler(CommandHandler("ownerinfo", owner_info_command))

    # ── Callback Queries ──────────────────────────────────

    # Force join verification
    app.add_handler(CallbackQueryHandler(handle_verify_stage1, pattern="^verify_stage1$"))
    app.add_handler(CallbackQueryHandler(handle_verify_stage2, pattern="^verify_stage2$"))

    # Navigation
    app.add_handler(CallbackQueryHandler(home_callback, pattern="^home$"))
    app.add_handler(CallbackQueryHandler(help_callback, pattern="^help$"))

    # File upload category selection
    app.add_handler(CallbackQueryHandler(handle_category_selection, pattern="^cat_"))

    # My Links pagination
    app.add_handler(CallbackQueryHandler(my_links_page_callback, pattern=r"^my_links_\d+$"))
    app.add_handler(CallbackQueryHandler(view_file_callback, pattern="^viewfile_"))
    app.add_handler(CallbackQueryHandler(file_stats_callback, pattern="^filestats_"))
    app.add_handler(CallbackQueryHandler(copy_link_callback, pattern="^copylink_"))
    app.add_handler(CallbackQueryHandler(delete_file_callback, pattern="^delfile_"))
    app.add_handler(CallbackQueryHandler(confirm_delete_callback, pattern="^confirmdelete_"))
    app.add_handler(CallbackQueryHandler(my_stats_callback, pattern="^my_stats$"))

    # Settings
    app.add_handler(CallbackQueryHandler(settings_callback, pattern="^settings$"))
    app.add_handler(CallbackQueryHandler(toggle_notifications_callback, pattern="^toggle_notif$"))
    app.add_handler(CallbackQueryHandler(toggle_language_callback, pattern="^toggle_lang$"))

    # Admin panel
    app.add_handler(CallbackQueryHandler(admin_panel_callback, pattern="^admin_panel$"))
    app.add_handler(CallbackQueryHandler(admin_stats_callback, pattern="^admin_stats$"))
    app.add_handler(CallbackQueryHandler(admin_users_callback, pattern=r"^admin_users_\d+$"))
    app.add_handler(CallbackQueryHandler(admin_view_user_callback, pattern="^adminviewuser_"))
    app.add_handler(CallbackQueryHandler(admin_ban_callback, pattern="^ban_"))
    app.add_handler(CallbackQueryHandler(admin_unban_callback, pattern="^unban_"))
    app.add_handler(CallbackQueryHandler(admin_reset_verify_callback, pattern="^resetverify_"))
    app.add_handler(CallbackQueryHandler(admin_files_callback, pattern=r"^admin_files_\d+$"))
    app.add_handler(CallbackQueryHandler(admin_view_file_callback, pattern="^adminviewfile_"))
    app.add_handler(CallbackQueryHandler(admin_delete_file_callback, pattern="^admindelfile_"))
    app.add_handler(CallbackQueryHandler(admin_disable_file_callback, pattern="^disablefile_"))
    app.add_handler(CallbackQueryHandler(admin_mark_permanent_callback, pattern="^markperm_"))

    # Owner panel
    app.add_handler(CallbackQueryHandler(owner_panel_callback, pattern="^owner_panel$"))
    app.add_handler(CallbackQueryHandler(owner_admins_callback, pattern="^owner_admins$"))
    app.add_handler(CallbackQueryHandler(owner_bc_history_callback, pattern=r"^owner_bc_history_\d+$"))

    # Broadcast
    app.add_handler(CallbackQueryHandler(start_broadcast_flow, pattern="^(admin_broadcast|owner_broadcast)$"))
    app.add_handler(CallbackQueryHandler(execute_broadcast_callback, pattern="^(bc_all|bc_active|bc_test)$"))
    app.add_handler(CallbackQueryHandler(stop_broadcast_callback, pattern="^stop_bc_"))
    app.add_handler(CallbackQueryHandler(cancel_broadcast_callback, pattern="^cancel_broadcast$"))

    # Upload info callback
    app.add_handler(CallbackQueryHandler(
        lambda u, c: u.callback_query.answer("📤 Just send me any file!"),
        pattern="^upload_info$",
    ))

    # ── All messages (smart router) ────────────────────────
    app.add_handler(MessageHandler(
        filters.ALL & ~filters.COMMAND,
        smart_message_router,
    ))

    # ── Error handler ──────────────────────────────────────
    app.add_error_handler(error_handler)

    logger.info("All handlers registered.")


# ── Main ───────────────────────────────────────────────────

def main() -> None:
    """Build and run the bot."""
    logger.info("Building application...")

    app = (
        Application.builder()
        .token(BOT_TOKEN)
        .post_init(on_startup)
        .post_shutdown(on_shutdown)
        .build()
    )

    register_handlers(app)

    logger.info("Starting polling...")
    app.run_polling(
        allowed_updates=Update.ALL_TYPES,
        drop_pending_updates=True,
    )


if __name__ == "__main__":
    main()
