# ============================================================
# File    : config.py
# Purpose : Load and validate all environment variables
# Author  : Generated by AI
# ============================================================

import os
import sys
import logging
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)


def _require(key: str) -> str:
    """Get a required environment variable or exit."""
    val = os.getenv(key)
    if not val:
        logger.critical(f"Missing required environment variable: {key}")
        sys.exit(1)
    return val


def _optional(key: str, default: str = "") -> str:
    return os.getenv(key, default)


def _int(key: str, default: int = 0) -> int:
    try:
        return int(os.getenv(key, str(default)))
    except ValueError:
        return default


# ── Bot ────────────────────────────────────────────────────
BOT_TOKEN: str = _require("BOT_TOKEN")
BOT_USERNAME: str = _require("BOT_USERNAME")

# ── Owner & Admins ─────────────────────────────────────────
OWNER_ID: int = int(_require("OWNER_ID"))

_admin_raw = _optional("ADMIN_IDS", "")
ADMIN_IDS: list[int] = [
    int(x.strip()) for x in _admin_raw.split(",") if x.strip().isdigit()
]

# ── MongoDB ────────────────────────────────────────────────
MONGODB_URI: str = _require("MONGODB_URI")
DB_NAME: str = _optional("DB_NAME", "filesharebotdb")

# ── Stage 1 Channels ───────────────────────────────────────
STAGE1_CHANNELS = [
    {
        "id": int(_require("CHANNEL_1_ID")),
        "link": _require("CHANNEL_1_LINK"),
        "name": _require("CHANNEL_1_NAME"),
    },
    {
        "id": int(_require("CHANNEL_2_ID")),
        "link": _require("CHANNEL_2_LINK"),
        "name": _require("CHANNEL_2_NAME"),
    },
    {
        "id": int(_require("CHANNEL_3_ID")),
        "link": _require("CHANNEL_3_LINK"),
        "name": _require("CHANNEL_3_NAME"),
    },
    {
        "id": int(_require("CHANNEL_4_ID")),
        "link": _require("CHANNEL_4_LINK"),
        "name": _require("CHANNEL_4_NAME"),
    },
]

# ── Stage 2 Channels ───────────────────────────────────────
STAGE2_CHANNELS = [
    {
        "id": int(_require("CHANNEL_5_ID")),
        "link": _require("CHANNEL_5_LINK"),
        "name": _require("CHANNEL_5_NAME"),
    },
    {
        "id": int(_require("CHANNEL_6_ID")),
        "link": _require("CHANNEL_6_LINK"),
        "name": _require("CHANNEL_6_NAME"),
    },
]

ALL_CHANNELS = STAGE1_CHANNELS + STAGE2_CHANNELS

# ── Optional ───────────────────────────────────────────────
LOG_CHANNEL_ID: int = _int("LOG_CHANNEL_ID", 0)
MAX_FILE_SIZE_MB: int = _int("MAX_FILE_SIZE_MB", 2000)
AUTO_DELETE_DAYS: int = _int("AUTO_DELETE_DAYS", 0)
RATE_LIMIT_REQUESTS: int = _int("RATE_LIMIT_REQUESTS", 5)
RATE_LIMIT_WINDOW: int = _int("RATE_LIMIT_WINDOW", 60)

# ── Derived ────────────────────────────────────────────────
MAX_FILE_SIZE_BYTES: int = MAX_FILE_SIZE_MB * 1024 * 1024
ALL_PRIVILEGED_IDS: list[int] = list(set([OWNER_ID] + ADMIN_IDS))

# ── Conversation States ────────────────────────────────────
class States:
    BROADCAST_WAITING_MSG = "broadcast_waiting_msg"
    BROADCAST_PREVIEW     = "broadcast_preview"
    SETTINGS_MENU         = "settings_menu"
    UPLOAD_CATEGORY       = "upload_category"
    BAN_WAITING_ID        = "ban_waiting_id"
    ADDADMIN_WAITING_ID   = "addadmin_waiting_id"

logger.info("Configuration loaded successfully.")
